function about() {
	document.getElementById("hide").classList.toggle("show");
	document.getElementById("video").classList.remove("show"); 
	document.getElementById("music").classList.remove("show");
	document.getElementById("tour").classList.remove("show");
	document.getElementById("s1").classList.remove("show");
	document.getElementById("s2").classList.remove("show");
	document.getElementById("s3").classList.remove("show");
	document.getElementById("s4").classList.remove("show");
	document.getElementById("s5").classList.remove("show");
	document.getElementById("s6").classList.remove("show");
	document.getElementById("s7").classList.remove("show");
	document.getElementById("s8").classList.remove("show");
	document.getElementById("s9").classList.remove("show");
	document.getElementById("s10").classList.remove("show");
	document.getElementById("s11").classList.remove("show");
	document.getElementById("s12").classList.remove("show");
	document.getElementById("s13").classList.remove("show");
	document.getElementById("s14").classList.remove("show");
	document.getElementById("s15").classList.remove("show");
	document.getElementById("s16").classList.remove("show");
	document.getElementById("s17").classList.remove("show");
	document.getElementById("s18").classList.remove("show");
	document.getElementById("s19").classList.remove("show");
	document.getElementById("s20").classList.remove("show");
	document.getElementById("s21").classList.remove("show");
	document.getElementById("s22").classList.remove("show");
	document.getElementById("s23").classList.remove("show");
	document.getElementById("s24").classList.remove("show");
	document.getElementById("s25").classList.remove("show");
	document.getElementById("s26").classList.remove("show");
	document.getElementById("s27").classList.remove("show");
	document.getElementById("imbml").classList.remove("show");
	document.getElementById("hmt").classList.remove("show");
	document.getElementById("inu").classList.remove("show");
	document.getElementById("se").classList.remove("show");
	document.getElementById("dope").classList.remove("show");
	document.getElementById("bwf").classList.remove("show");
	document.getElementById("ch").classList.remove("show");
	document.getElementById("mo").classList.remove("show");
	document.getElementById("olino").classList.remove("show");
	document.getElementById("inm").classList.remove("show");
	document.getElementById("run").classList.remove("show");
	document.getElementById("butterfly").classList.remove("show");
	document.getElementById("w52").classList.remove("show");
	document.getElementById("mc").classList.remove("show");
	document.getElementById("ss").classList.remove("show");
	document.getElementById("sonsc").classList.remove("show");
	document.getElementById("dl").classList.remove("show");
	document.getElementById("ohc").classList.remove("show");
	document.getElementById("bpr").classList.remove("show");
	document.getElementById("fire").classList.remove("show");
	document.getElementById("sm").classList.remove("show");
	document.getElementById("eyf").classList.remove("show");
	document.getElementById("inuum").classList.remove("show");
	document.getElementById("inur").classList.remove("show");
	document.getElementById("rbm").classList.remove("show");
	document.getElementById("ram").classList.remove("show");
	document.getElementById("bam").classList.remove("show");
}
function video() {
	document.getElementById("video").classList.toggle("show");
	document.getElementById("hide").classList.remove("show");
	document.getElementById("music").classList.remove("show");
	document.getElementById("tour").classList.remove("show");
	document.getElementById("s1").classList.remove("show");
	document.getElementById("s2").classList.remove("show");
	document.getElementById("s3").classList.remove("show");
	document.getElementById("s4").classList.remove("show");
	document.getElementById("s5").classList.remove("show");
	document.getElementById("s6").classList.remove("show");
	document.getElementById("s7").classList.remove("show");
	document.getElementById("s8").classList.remove("show");
	document.getElementById("s9").classList.remove("show");
	document.getElementById("s10").classList.remove("show");
	document.getElementById("s11").classList.remove("show");
	document.getElementById("s12").classList.remove("show");
	document.getElementById("s13").classList.remove("show");
	document.getElementById("s14").classList.remove("show");
	document.getElementById("s15").classList.remove("show");
	document.getElementById("s16").classList.remove("show");
	document.getElementById("s17").classList.remove("show");
	document.getElementById("s18").classList.remove("show");
	document.getElementById("s19").classList.remove("show");
	document.getElementById("s20").classList.remove("show");
	document.getElementById("s21").classList.remove("show");
	document.getElementById("s22").classList.remove("show");
	document.getElementById("s23").classList.remove("show");
	document.getElementById("s24").classList.remove("show");
	document.getElementById("s25").classList.remove("show");
	document.getElementById("s26").classList.remove("show");
	document.getElementById("s27").classList.remove("show");
	document.getElementById("imbml").classList.remove("show");
	document.getElementById("hmt").classList.remove("show");
	document.getElementById("inu").classList.remove("show");
	document.getElementById("se").classList.remove("show");
	document.getElementById("dope").classList.remove("show");
	document.getElementById("bwf").classList.remove("show");
	document.getElementById("ch").classList.remove("show");
	document.getElementById("mo").classList.remove("show");
	document.getElementById("olino").classList.remove("show");
	document.getElementById("inm").classList.remove("show");
	document.getElementById("run").classList.remove("show");
	document.getElementById("butterfly").classList.remove("show");
	document.getElementById("w52").classList.remove("show");
	document.getElementById("mc").classList.remove("show");
	document.getElementById("ss").classList.remove("show");
	document.getElementById("sonsc").classList.remove("show");
	document.getElementById("dl").classList.remove("show");
	document.getElementById("ohc").classList.remove("show");
	document.getElementById("bpr").classList.remove("show");
	document.getElementById("fire").classList.remove("show");
	document.getElementById("sm").classList.remove("show");
	document.getElementById("eyf").classList.remove("show");
	document.getElementById("inuum").classList.remove("show");
	document.getElementById("inur").classList.remove("show");
	document.getElementById("rbm").classList.remove("show");
	document.getElementById("ram").classList.remove("show");
	document.getElementById("bam").classList.remove("show");
}
function music() {
	document.getElementById("music").classList.toggle("show");
	document.getElementById("hide").classList.remove("show");
	document.getElementById("video").classList.remove("show");
	document.getElementById("tour").classList.remove("show");
	document.getElementById("s1").classList.remove("show");
	document.getElementById("s2").classList.remove("show");
	document.getElementById("s3").classList.remove("show");
	document.getElementById("s4").classList.remove("show");
	document.getElementById("s5").classList.remove("show");
	document.getElementById("s6").classList.remove("show");
	document.getElementById("s7").classList.remove("show");
	document.getElementById("s8").classList.remove("show");
	document.getElementById("s9").classList.remove("show");
	document.getElementById("s10").classList.remove("show");
	document.getElementById("s11").classList.remove("show");
	document.getElementById("s12").classList.remove("show");
	document.getElementById("s13").classList.remove("show");
	document.getElementById("s14").classList.remove("show");
	document.getElementById("s15").classList.remove("show");
	document.getElementById("s16").classList.remove("show");
	document.getElementById("s17").classList.remove("show");
	document.getElementById("s18").classList.remove("show");
	document.getElementById("s19").classList.remove("show");
	document.getElementById("s20").classList.remove("show");
	document.getElementById("s21").classList.remove("show");
	document.getElementById("s22").classList.remove("show");
	document.getElementById("s23").classList.remove("show");
	document.getElementById("s24").classList.remove("show");
	document.getElementById("s25").classList.remove("show");
	document.getElementById("s26").classList.remove("show");
	document.getElementById("s27").classList.remove("show");
	document.getElementById("imbml").classList.remove("show");
	document.getElementById("hmt").classList.remove("show");
	document.getElementById("inu").classList.remove("show");
	document.getElementById("se").classList.remove("show");
	document.getElementById("dope").classList.remove("show");
	document.getElementById("bwf").classList.remove("show");
	document.getElementById("ch").classList.remove("show");
	document.getElementById("mo").classList.remove("show");
	document.getElementById("olino").classList.remove("show");
	document.getElementById("inm").classList.remove("show");
	document.getElementById("run").classList.remove("show");
	document.getElementById("butterfly").classList.remove("show");
	document.getElementById("w52").classList.remove("show");
	document.getElementById("mc").classList.remove("show");
	document.getElementById("ss").classList.remove("show");
	document.getElementById("sonsc").classList.remove("show");
	document.getElementById("dl").classList.remove("show");
	document.getElementById("ohc").classList.remove("show");
	document.getElementById("bpr").classList.remove("show");
	document.getElementById("fire").classList.remove("show");
	document.getElementById("sm").classList.remove("show");
	document.getElementById("eyf").classList.remove("show");
	document.getElementById("inuum").classList.remove("show");
	document.getElementById("inur").classList.remove("show");
	document.getElementById("rbm").classList.remove("show");
	document.getElementById("ram").classList.remove("show");
	document.getElementById("bam").classList.remove("show");
}
function tour() {
	document.getElementById("tour").classList.toggle("show");
	document.getElementById("hide").classList.remove("show");
	document.getElementById("video").classList.remove("show");
	document.getElementById("music").classList.remove("show");
	document.getElementById("s1").classList.remove("show");
	document.getElementById("s2").classList.remove("show");
	document.getElementById("s3").classList.remove("show");
	document.getElementById("s4").classList.remove("show");
	document.getElementById("s5").classList.remove("show");
	document.getElementById("s6").classList.remove("show");
	document.getElementById("s7").classList.remove("show");
	document.getElementById("s8").classList.remove("show");
	document.getElementById("s9").classList.remove("show");
	document.getElementById("s10").classList.remove("show");
	document.getElementById("s11").classList.remove("show");
	document.getElementById("s12").classList.remove("show");
	document.getElementById("s13").classList.remove("show");
	document.getElementById("s14").classList.remove("show");
	document.getElementById("s15").classList.remove("show");
	document.getElementById("s16").classList.remove("show");
	document.getElementById("s17").classList.remove("show");
	document.getElementById("s18").classList.remove("show");
	document.getElementById("s19").classList.remove("show");
	document.getElementById("s20").classList.remove("show");
	document.getElementById("s21").classList.remove("show");
	document.getElementById("s22").classList.remove("show");
	document.getElementById("s23").classList.remove("show");
	document.getElementById("s24").classList.remove("show");
	document.getElementById("s25").classList.remove("show");
	document.getElementById("s26").classList.remove("show");
	document.getElementById("s27").classList.remove("show");
	document.getElementById("imbml").classList.remove("show");
	document.getElementById("hmt").classList.remove("show");
	document.getElementById("inu").classList.remove("show");
	document.getElementById("se").classList.remove("show");
	document.getElementById("dope").classList.remove("show");
	document.getElementById("bwf").classList.remove("show");
	document.getElementById("ch").classList.remove("show");
	document.getElementById("mo").classList.remove("show");
	document.getElementById("olino").classList.remove("show");
	document.getElementById("inm").classList.remove("show");
	document.getElementById("run").classList.remove("show");
	document.getElementById("butterfly").classList.remove("show");
	document.getElementById("w52").classList.remove("show");
	document.getElementById("mc").classList.remove("show");
	document.getElementById("ss").classList.remove("show");
	document.getElementById("sonsc").classList.remove("show");
	document.getElementById("dl").classList.remove("show");
	document.getElementById("ohc").classList.remove("show");
	document.getElementById("bpr").classList.remove("show");
	document.getElementById("fire").classList.remove("show");
	document.getElementById("sm").classList.remove("show");
	document.getElementById("eyf").classList.remove("show");
	document.getElementById("inuum").classList.remove("show");
	document.getElementById("inur").classList.remove("show");
	document.getElementById("rbm").classList.remove("show");
	document.getElementById("ram").classList.remove("show");
	document.getElementById("bam").classList.remove("show");
}
function track() {
	document.getElementById("hide").classList.remove("show");
	document.getElementById("video").classList.remove("show");
	document.getElementById("music").classList.remove("show");
	document.getElementById("tour").classList.remove("show");
	document.getElementById("s1").classList.toggle("show");
	document.getElementById("s2").classList.toggle("show");
	document.getElementById("s3").classList.toggle("show");
	document.getElementById("s4").classList.toggle("show");
	document.getElementById("s5").classList.toggle("show");
	document.getElementById("s6").classList.toggle("show");
	document.getElementById("s7").classList.toggle("show");
	document.getElementById("s8").classList.toggle("show");
	document.getElementById("s9").classList.toggle("show");
	document.getElementById("s10").classList.toggle("show");
	document.getElementById("s11").classList.toggle("show");
	document.getElementById("s12").classList.toggle("show");
	document.getElementById("s13").classList.toggle("show");
	document.getElementById("s14").classList.toggle("show");
	document.getElementById("s15").classList.toggle("show");
	document.getElementById("s16").classList.toggle("show");
	document.getElementById("s17").classList.toggle("show");
	document.getElementById("s18").classList.toggle("show");
	document.getElementById("s19").classList.toggle("show");
	document.getElementById("s20").classList.toggle("show");
	document.getElementById("s21").classList.toggle("show");
	document.getElementById("s22").classList.toggle("show");
	document.getElementById("s23").classList.toggle("show");
	document.getElementById("s24").classList.toggle("show");
	document.getElementById("s25").classList.toggle("show");
	document.getElementById("s26").classList.toggle("show");
	document.getElementById("s27").classList.toggle("show");
	document.getElementById("imbml").classList.remove("show");
	document.getElementById("hmt").classList.remove("show");
	document.getElementById("inu").classList.remove("show");
	document.getElementById("se").classList.remove("show");
	document.getElementById("dope").classList.remove("show");
	document.getElementById("bwf").classList.remove("show");
	document.getElementById("ch").classList.remove("show");
	document.getElementById("mo").classList.remove("show");
	document.getElementById("olino").classList.remove("show");
	document.getElementById("inm").classList.remove("show");
	document.getElementById("run").classList.remove("show");
	document.getElementById("butterfly").classList.remove("show");
	document.getElementById("w52").classList.remove("show");
	document.getElementById("mc").classList.remove("show");
	document.getElementById("ss").classList.remove("show");
	document.getElementById("sonsc").classList.remove("show");
	document.getElementById("dl").classList.remove("show");
	document.getElementById("ohc").classList.remove("show");
	document.getElementById("bpr").classList.remove("show");
	document.getElementById("fire").classList.remove("show");
	document.getElementById("sm").classList.remove("show");
	document.getElementById("eyf").classList.remove("show");
	document.getElementById("inuum").classList.remove("show");
	document.getElementById("inur").classList.remove("show");
	document.getElementById("rbm").classList.remove("show");
	document.getElementById("ram").classList.remove("show");
	document.getElementById("bam").classList.remove("show");
}

function playimbml() {
	document.getElementById("imbml").classList.toggle("show");
}
function playhmt() {
	document.getElementById("hmt").classList.toggle("show");
}
function playinu() {
	document.getElementById("inu").classList.toggle("show");
}
function playse() {
	document.getElementById("se").classList.toggle("show");
}
function playdope() {
	document.getElementById("dope").classList.toggle("show");
}
function playbwf() {
	document.getElementById("bwf").classList.toggle("show");
}
function playch() {
	document.getElementById("ch").classList.toggle("show");
}
function playmo() {
	document.getElementById("mo").classList.toggle("show");
}
function playolino() {
	document.getElementById("olino").classList.toggle("show");
}
function playinm() {
	document.getElementById("inm").classList.toggle("show");
}
function playrun() {
	document.getElementById("run").classList.toggle("show");
}
function playbutterfly() {
	document.getElementById("butterfly").classList.toggle("show");
}
function playw52() {
	document.getElementById("w52").classList.toggle("show");
}
function playmc() {
	document.getElementById("mc").classList.toggle("show");
}
function playss() {
	document.getElementById("ss").classList.toggle("show");
}
function playsonsc() {
	document.getElementById("sonsc").classList.toggle("show");
}
function playdl() {
	document.getElementById("dl").classList.toggle("show");
}
function playohc() {
	document.getElementById("ohc").classList.toggle("show");
}
function playbpr() {
	document.getElementById("bpr").classList.toggle("show");
}
function playfire() {
	document.getElementById("fire").classList.toggle("show");
}
function playsm() {
	document.getElementById("sm").classList.toggle("show");
}
function playeyf() {
	document.getElementById("eyf").classList.toggle("show");
}
function playinuum() {
	document.getElementById("inuum").classList.toggle("show");
}
function playinur() {
	document.getElementById("inur").classList.toggle("show");
}
function playrbm() {
	document.getElementById("rbm").classList.toggle("show");
}
function playram() {
	document.getElementById("ram").classList.toggle("show");
}
function playbam() {
	document.getElementById("bam").classList.toggle("show");
}
